{
 "title": "Homebrew AQI - With Environment",
 "tags": [
  "InfluxDB",
  "Telegraf",
  "homebrew_aqi"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Average", "query": "1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Outside AQI",
     "measurement": "homebrew_aqi",
     "query": "// Interpolate a value in a range to a new range\r\ninterpolate = (lowVal, highVal, lowOut, highOut, value) => lowOut + (highOut-lowOut)*(value-lowVal)/(highVal-lowVal)\r\n\r\n// Calculate the AQI from a pm2.5 count from\r\n// https://www.epa.gov/sites/production/files/2016-04/documents/2012_aqi_factsheet.pdf\r\ncalcAQI = (val) => if not exists val then val\r\n      else if val <= 12.0 then interpolate(lowVal:0.0, highVal:12.0, lowOut:0.0, highOut:50.0, value:val)\r\n      else if val <= 35.4 then interpolate(lowVal:12.0, highVal:35.4, lowOut:50.0, highOut:100.0, value:val)\r\n      else if val <= 55.4 then interpolate(lowVal:35.4, highVal:55.4, lowOut:100.0, highOut:150.0, value:val)\r\n      else if val <= 150.4 then interpolate(lowVal:55.4, highVal:150.4, lowOut:150.0, highOut:200.0, value:val)\r\n      else if val <= 250.4 then interpolate(lowVal:150.4, highVal:250.4, lowOut:200.0, highOut:300.0, value:val)\r\n      else if val <= 350.4 then interpolate(lowVal:250.4, highVal:350.4, lowOut:300.0, highOut:400.0, value:val)\r\n      else interpolate(lowVal:350.4, highVal:500.0, lowOut:400.0, highOut:500.0, value:val)\r\n\r\n// Map row values to AQI\r\nmapToAQI = (tables=<-) =>\r\n  tables\r\n    |> map(fn: (r) => ({ r with _value: calcAQI(val: r._value)}))\r\n\r\n// Query for the PM2.5 count and conert to AQI\r\nfrom(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"homebrew_aqi\" )\r\n  |> filter(fn: (r) => r._field == \"mass_density_pm2p5\")\r\n  |> group()\r\n  |> aggregateWindow(every: ${Average}, fn: mean)\r\n  |> mapToAQI()\r\n  |> rename(columns: {_value: \"AQI\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Inside temp",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "homebrew_aqi",
     "query": "SELECT mean(\"environment_temperature\")*9/5+32 FROM \"homebrew_aqi\" WHERE $timeFilter GROUP BY time($Average)",
     "select": [
      [
       { "params": [ "environment_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "homebrew_aqi",
     "query": "SELECT mean(\"environment_humidity\") FROM \"homebrew_aqi\" WHERE $timeFilter GROUP BY time($Average)",
     "select": [
      [
       { "params": [ "environment_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Pressure",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "homebrew_aqi",
     "query": "SELECT mean(\"environment_pressure\") FROM \"homebrew_aqi\" WHERE $timeFilter GROUP BY time($Average)",
     "select": [
      [
       { "params": [ "environment_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "homebrew_aqi",
     "query": "// Interpolate a value in a range to a new range\r\ninterpolate = (lowVal, highVal, lowOut, highOut, value) => lowOut + (highOut-lowOut)*(value-lowVal)/(highVal-lowVal)\r\n\r\n// Calculate the AQI from a pm2.5 count from\r\n// https://www.epa.gov/sites/production/files/2016-04/documents/2012_aqi_factsheet.pdf\r\ncalcAQI = (val) => if not exists val then val\r\n      else if val <= 12.0 then interpolate(lowVal:0.0, highVal:12.0, lowOut:0.0, highOut:50.0, value:val)\r\n      else if val <= 35.4 then interpolate(lowVal:12.0, highVal:35.4, lowOut:50.0, highOut:100.0, value:val)\r\n      else if val <= 55.4 then interpolate(lowVal:35.4, highVal:55.4, lowOut:100.0, highOut:150.0, value:val)\r\n      else if val <= 150.4 then interpolate(lowVal:55.4, highVal:150.4, lowOut:150.0, highOut:200.0, value:val)\r\n      else if val <= 250.4 then interpolate(lowVal:150.4, highVal:250.4, lowOut:200.0, highOut:300.0, value:val)\r\n      else if val <= 350.4 then interpolate(lowVal:250.4, highVal:350.4, lowOut:300.0, highOut:400.0, value:val)\r\n      else interpolate(lowVal:350.4, highVal:500.0, lowOut:400.0, highOut:500.0, value:val)\r\n\r\n// Map row values to AQI\r\nmapToAQI = (tables=<-) =>\r\n  tables\r\n    |> map(fn: (r) => ({ r with _value: calcAQI(val: r._value)}))\r\n\r\n// Query for the PM2.5 count and conert to AQI\r\nfrom(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"homebrew_aqi\" )\r\n  |> filter(fn: (r) => r._field == \"mass_density_pm2p5\")\r\n  |> group()\r\n  |> aggregateWindow(every: ${Average}, fn: mean)\r\n  |> mapToAQI()\r\n  |> rename(columns: {_value: \"AQI\"})\r\n  |> yield()"
    }
   ]
  },
  { "title": "Air Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "AQI Outside",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "homebrew_aqi",
     "query": "// Interpolate a value in a range to a new range\r\ninterpolate = (lowVal, highVal, lowOut, highOut, value) => lowOut + (highOut-lowOut)*(value-lowVal)/(highVal-lowVal)\r\n\r\n// Calculate the AQI from a pm2.5 count from\r\n// https://www.epa.gov/sites/production/files/2016-04/documents/2012_aqi_factsheet.pdf\r\ncalcAQI = (val) => if not exists val then val\r\n      else if val <= 12.0 then interpolate(lowVal:0.0, highVal:12.0, lowOut:0.0, highOut:50.0, value:val)\r\n      else if val <= 35.4 then interpolate(lowVal:12.0, highVal:35.4, lowOut:50.0, highOut:100.0, value:val)\r\n      else if val <= 55.4 then interpolate(lowVal:35.4, highVal:55.4, lowOut:100.0, highOut:150.0, value:val)\r\n      else if val <= 150.4 then interpolate(lowVal:55.4, highVal:150.4, lowOut:150.0, highOut:200.0, value:val)\r\n      else if val <= 250.4 then interpolate(lowVal:150.4, highVal:250.4, lowOut:200.0, highOut:300.0, value:val)\r\n      else if val <= 350.4 then interpolate(lowVal:250.4, highVal:350.4, lowOut:300.0, highOut:400.0, value:val)\r\n      else interpolate(lowVal:350.4, highVal:500.0, lowOut:400.0, highOut:500.0, value:val)\r\n\r\n// Map row values to AQI\r\nmapToAQI = (tables=<-) =>\r\n  tables\r\n    |> map(fn: (r) => ({ r with _value: calcAQI(val: r._value)}))\r\n\r\n// Query for the PM2.5 count and conert to AQI\r\nfrom(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"homebrew_aqi\" )\r\n  |> filter(fn: (r) => r._field == \"mass_density_pm2p5\")\r\n  |> group(columns: [\"sensor_id\",\"SensorId\"], mode: \"by\")\r\n  |> aggregateWindow(every: ${Average}, fn: mean)\r\n  |> mapToAQI()\r\n  |> yield()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Outside Avg",
     "measurement": "homebrew_aqi",
     "query": "// Interpolate a value in a range to a new range\r\ninterpolate = (lowVal, highVal, lowOut, highOut, value) => lowOut + (highOut-lowOut)*(value-lowVal)/(highVal-lowVal)\r\n\r\n// Calculate the AQI from a pm2.5 count from\r\n// https://www.epa.gov/sites/production/files/2016-04/documents/2012_aqi_factsheet.pdf\r\ncalcAQI = (val) => if not exists val then val\r\n      else if val <= 12.0 then interpolate(lowVal:0.0, highVal:12.0, lowOut:0.0, highOut:50.0, value:val)\r\n      else if val <= 35.4 then interpolate(lowVal:12.0, highVal:35.4, lowOut:50.0, highOut:100.0, value:val)\r\n      else if val <= 55.4 then interpolate(lowVal:35.4, highVal:55.4, lowOut:100.0, highOut:150.0, value:val)\r\n      else if val <= 150.4 then interpolate(lowVal:55.4, highVal:150.4, lowOut:150.0, highOut:200.0, value:val)\r\n      else if val <= 250.4 then interpolate(lowVal:150.4, highVal:250.4, lowOut:200.0, highOut:300.0, value:val)\r\n      else if val <= 350.4 then interpolate(lowVal:250.4, highVal:350.4, lowOut:300.0, highOut:400.0, value:val)\r\n      else interpolate(lowVal:350.4, highVal:500.0, lowOut:400.0, highOut:500.0, value:val)\r\n\r\n// Map row values to AQI\r\nmapToAQI = (tables=<-) =>\r\n  tables\r\n    |> map(fn: (r) => ({ r with _value: calcAQI(val: r._value)}))\r\n\r\n// Query for the PM2.5 count and conert to AQI\r\nfrom(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"homebrew_aqi\" )\r\n  |> filter(fn: (r) => r._field == \"mass_density_pm2p5\")\r\n  |> group()\r\n  |> mean() \r\n  |> mapToAQI()\r\n  |> rename(columns: {_value: \"Avg AQI\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "alias": "Min",
     "measurement": "homebrew_aqi",
     "query": "// Interpolate a value in a range to a new range\r\ninterpolate = (lowVal, highVal, lowOut, highOut, value) => lowOut + (highOut-lowOut)*(value-lowVal)/(highVal-lowVal)\r\n\r\n// Calculate the AQI from a pm2.5 count from\r\n// https://www.epa.gov/sites/production/files/2016-04/documents/2012_aqi_factsheet.pdf\r\ncalcAQI = (val) => if not exists val then val\r\n      else if val <= 12.0 then interpolate(lowVal:0.0, highVal:12.0, lowOut:0.0, highOut:50.0, value:val)\r\n      else if val <= 35.4 then interpolate(lowVal:12.0, highVal:35.4, lowOut:50.0, highOut:100.0, value:val)\r\n      else if val <= 55.4 then interpolate(lowVal:35.4, highVal:55.4, lowOut:100.0, highOut:150.0, value:val)\r\n      else if val <= 150.4 then interpolate(lowVal:55.4, highVal:150.4, lowOut:150.0, highOut:200.0, value:val)\r\n      else if val <= 250.4 then interpolate(lowVal:150.4, highVal:250.4, lowOut:200.0, highOut:300.0, value:val)\r\n      else if val <= 350.4 then interpolate(lowVal:250.4, highVal:350.4, lowOut:300.0, highOut:400.0, value:val)\r\n      else interpolate(lowVal:350.4, highVal:500.0, lowOut:400.0, highOut:500.0, value:val)\r\n\r\n// Map row values to AQI\r\nmapToAQI = (tables=<-) =>\r\n  tables\r\n    |> map(fn: (r) => ({ r with _value: calcAQI(val: r._value)}))\r\n\r\n// Query for the PM2.5 count and conert to AQI\r\nfrom(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"homebrew_aqi\" )\r\n  |> filter(fn: (r) => r._field == \"mass_density_pm2p5\")\r\n  |> group()\r\n  |> min() \r\n  |> mapToAQI()\r\n  |> rename(columns: {_value: \"Min\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Max",
     "measurement": "homebrew_aqi",
     "query": "// Interpolate a value in a range to a new range\r\ninterpolate = (lowVal, highVal, lowOut, highOut, value) => lowOut + (highOut-lowOut)*(value-lowVal)/(highVal-lowVal)\r\n\r\n// Calculate the AQI from a pm2.5 count from\r\n// https://www.epa.gov/sites/production/files/2016-04/documents/2012_aqi_factsheet.pdf\r\ncalcAQI = (val) => if not exists val then val\r\n      else if val <= 12.0 then interpolate(lowVal:0.0, highVal:12.0, lowOut:0.0, highOut:50.0, value:val)\r\n      else if val <= 35.4 then interpolate(lowVal:12.0, highVal:35.4, lowOut:50.0, highOut:100.0, value:val)\r\n      else if val <= 55.4 then interpolate(lowVal:35.4, highVal:55.4, lowOut:100.0, highOut:150.0, value:val)\r\n      else if val <= 150.4 then interpolate(lowVal:55.4, highVal:150.4, lowOut:150.0, highOut:200.0, value:val)\r\n      else if val <= 250.4 then interpolate(lowVal:150.4, highVal:250.4, lowOut:200.0, highOut:300.0, value:val)\r\n      else if val <= 350.4 then interpolate(lowVal:250.4, highVal:350.4, lowOut:300.0, highOut:400.0, value:val)\r\n      else interpolate(lowVal:350.4, highVal:500.0, lowOut:400.0, highOut:500.0, value:val)\r\n\r\n// Map row values to AQI\r\nmapToAQI = (tables=<-) =>\r\n  tables\r\n    |> map(fn: (r) => ({ r with _value: calcAQI(val: r._value)}))\r\n\r\n// Query for the PM2.5 count and conert to AQI\r\nfrom(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"homebrew_aqi\" )\r\n  |> filter(fn: (r) => r._field == \"mass_density_pm2p5\")\r\n  |> group()\r\n  |> aggregateWindow(every: ${Average}, fn: mean)\r\n  |> max() \r\n  |> mapToAQI()\r\n  |> rename(columns: {_value: \"Max\"})\r\n  |> yield()"
    }
   ]
  },
  { "title": "Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Indoor temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Indoor Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "homebrew_aqi",
     "query": "SELECT mean(\"environment_temperature\")*9/5+32 FROM \"homebrew_aqi\" WHERE $timeFilter GROUP BY time($Average) fill(null)",
     "select": [
      [
       { "params": [ "environment_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "has_bme680", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Indoor humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "homebrew_aqi",
     "query": "SELECT mean(\"environment_humidity\") FROM \"homebrew_aqi\" WHERE $timeFilter GROUP BY time($Average) fill(null)",
     "select": [
      [
       { "params": [ "environment_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indoor Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "mb" }
   ],
   "targets": [
    {
     "alias": "Pressure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "homebrew_aqi",
     "query": "SELECT mean(\"environment_pressure\") FROM \"homebrew_aqi\" WHERE $timeFilter GROUP BY time($Average) fill(none)",
     "select": [
      [
       { "params": [ "environment_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas resistance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "VOC (iaq)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "homebrew_aqi",
     "query": "SELECT mean(\"environment_gas_resistance\") FROM \"homebrew_aqi\" WHERE $timeFilter GROUP BY time($Average) fill(null)",
     "select": [
      [
       { "params": [ "environment_gas_resistance" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}