apiVersion: 1

deleteDatasources:
  - name: InfluxDBFlux_test

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    isDefault: true
    url: http://influxdb:8086
    database: telegraf
    user: telegraf
    secureJsonData:
      password: changeme
    jsonData:
      httpMode: GET
      